pipeline {
	agent any
	stages {
		stage('Lint html') {
			steps {
					sh '''
					    tidy deploy-bg/*.html
					'''
			}
		}
		stage('Build Docker Image') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'uda-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						docker build -t fran6cu/udacity_capstone -f deploy-bg/Dockerfile .
					'''
				}
			}
		}
		stage('Push Docker Image to Dockerhub') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'uda-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
						docker push fran6cu/udacity_capstone
					'''
				}
			}
		}

		stage('Set kubectl config') {
			steps {
				withAWS(region:'us-east-1', credentials:'uda-credentials') {
					sh '''
						kubectl config use-context arn:aws:eks:us-east-1:474880089665:cluster/udacitycapstonecluster14
					'''
				}
			}
		}
		stage('Blue') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						kubectl apply -f blue_green_deploy/blue.controller.json
					'''
				}
			}
		}
		stage('Apply the green container') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						kubectl apply -f blue_green_deploy/green.controller.json
					'''
				}
			}
		}
		stage('Apply the blue service within udacitycapstonecluster14') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						kubectl apply -f blue_green_deploy/blue.service.json
					'''
				}
			}
		}
		stage('Wait to redirect the traffic to the green service') {
            steps {
                input "Wait to redirect the traffic to the green service"
            }
        }
		stage('Apply the green service within udacitycapstonecluster14') {
			steps {
				withAWS(region:'us-east-1', credentials:'jenkins_udacity_cloud_devops_capstone') {
					sh '''
						kubectl apply -f blue_green_deploy/green.service.json
					'''
				}
			}
		}
	}
}
