pipeline {
	agent any
	stages {
		stage('Lint html') {
			steps {
					sh '''
					    tidy deploy-bg/*.html
					'''
			}
		}
		stage('Build Docker Image') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Jenkins', usernameVariable: 'usrdocker', passwordVariable: 'pwddocker']]){
					sh '''
						docker build -t fran6cu/udacity_capstone -f deploy-bg/Dockerfile .
					'''
				}
			}
		}
		stage('Push Docker Image to Dockerhub') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'Jenkins', usernameVariable: 'usrdocker', passwordVariable: 'pwddocker']]){
					sh '''
						docker login -u $usrdocker -p $pwddocker
						docker push fran6cu/udacity_capstone
					'''
				}
			}
		}

		stage('Set kubectl config') {
			steps {
				withAWS(region:'us-east-2', credentials:'Jenkins') {
					sh '''
						kubectl config use-context arn:aws:eks:us-east-2:088642813079:cluster/udacity-cluster-eks
					'''
				}
			}
		}
		stage('Blue') {
			steps {
				withAWS(region:'us-east-2', credentials:'Jenkins') {
					sh '''
						kubectl apply -f deploy-bg/blue.controller.json
					'''
				}
			}
		}
		stage('Green') {
			steps {
				withAWS(region:'us-east-2', credentials:'Jenkins') {
					sh '''
						kubectl apply -f deploy-bg/green.controller.json
					'''
				}
			}
		}
		stage('Apply Blue') {
			steps {
				withAWS(region:'us-east-2', credentials:'Jenkins') {
					sh '''
						kubectl apply -f deploy-bg/blue.service.json
					'''
				}
			}
		}
		stage('Redirecting to the green ...') {
            steps {
                input "Wait to redirect the traffic to the green service"
            }
        }
		stage('Applying the green service within cluster') {
			steps {
				withAWS(region:'us-east-2', credentials:'Jenkins') {
					sh '''
						kubectl apply -f deploy-bg/green.service.json
					'''
				}
			}
		}
	}
}
