pipeline {
	agent any
	stages {
		stage('Create a k8s cluster') {
			steps {
				withAWS(region:'us-east-2', credentials:'Jenkins') {
					sh '''
						eksctl create cluster \
						--name udacity-cluster-eks \
						--version 1.13 \
						--nodegroup-name udacity-workers-eks \
						--node-type t2.small \
						--nodes 2 \
						--nodes-min 1 \
						--nodes-max 3 \
						--node-ami auto \
						--region us-east-2 \
						--zones us-east-2a \
						--zones us-east-2b \
						--zones us-east-2c \
					'''
				}
			}
		}

	//	stage('Get Configuration File') {
	//		steps {
	//			withAWS(region:'us-east-2', credentials:'Jenkins') {
	//				sh '''
	//					aws eks --region us-east-2 update-kubeconfig --name udacity-cluster-eks
	//				'''
	//			}
	//		}
	//	}
	}
}
